---
# tasks file for prometheus_opensuse
- name: Install Prometheus
  zypper:
    name: golang-github-prometheus-prometheus
    state: latest
    update_cache: yes

- name: Start Prometheus
  service:
    name: prometheus
    state: started

