---
# tasks file for clone-prelim_opensuse
- name: Create a Directory
  file:
    path: /home/ronel_23/repository
    state: directory
    mode: '777'

- name: Install Git
  zypper:
    name: git
    state: latest
    update_cache: yes

- name: Clone Prelim Exam Repository
  git:
    repo: 'https://github.com/rgerman-tip/sysad2-12021.git'
    dest: /home/ronel_23/repository
    version: prelim-exam
    clone: yes
    update: yes

