---
# tasks file for prometheus_ubuntu
- name: Install Prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: Start Prometheus
  service:
    name: prometheus
    state: started

